import Head from 'next/head';

import styles from './index.module.scss';

import CardPost from '@/components/CardPost/CardPost';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<section className={styles['page']}>
					<div className={`container ${styles['page-container']}`}>
						<h1>Últimos artidos do Minimal Blog</h1>

						<div className={styles['page-content']}>
							<CardPost />
							<CardPost />
							<CardPost />
						</div>
					</div>
				</section>
			</main>
		</>
	);
}
